spring:
  profiles:
    active: dev #默认为开发环境

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

http:
  port: 8085 # http服务端口

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 90 # 验证码超期时间

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue


# 第三方支付
pay-info:
  merchantNo: 2000078
  notifyUrl: http://47.52.130.84:8085/onePage/paySuccess
  signKey: pybYm4VYFAN76xVUDkDZgG7yfff6rBPv045AZFNhsEzpAbe117

# ISPAY支付
is-pay:
  payId: 12672
  payChannel: wxpay
  Notify_url: http://47.52.130.84:8085/onePage/isPaySuccess
  payKey: 087fa038a57f2192023c44eb77e14620




